services:
  native-tauri:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/native-tauri:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/developer/.Xauthority:rw
    environment:
      TZ: ${TZ} # Timezone
      GITHUB_TOKEN: ${GITHUB_TOKEN} # Github CLI
      RUST_LOG: debug # Syntax: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#example-syntax
      # For GUI
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PULSE_SERVER: ${PULSE_SERVER}
    # Optional but recommended for GUI apps
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined